"""shows model added

Revision ID: 17968ecb1e75
Revises: cf2710015876
Create Date: 2021-02-22 03:30:33.971070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17968ecb1e75'
down_revision = 'cf2710015876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Shows')
    # ### end Alembic commands ###
